# Generated by Django 6.1.1 on 2026-09-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_booking_bookingseat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingseat',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingseat',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='show',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='show',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingSeat',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Show',
        ),
    ]
