# Generated by Django 6.1.1 on 2026-09-23 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_booking_show_alter_booking_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='base.movie'),
        ),
        migrations.AddConstraint(
            model_name='bookingseat',
            constraint=models.UniqueConstraint(fields=('seat',), name='unique_seat_booking'),
        ),
    ]
