# Generated by Django 6.1.1 on 2026-09-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_show_movie_bookingseat_unique_seat_booking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookingseat',
            name='unique_seat_booking',
        ),
    ]
