# Generated by Django 6.1.1 on 2026-09-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_bookingseat_unique_seat_booking'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookingseat',
            constraint=models.UniqueConstraint(fields=('seat',), name='unique_seat_booking'),
        ),
    ]
