# Generated by Django 6.1.1 on 2026-09-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_bookingseat_unique_seat_booking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookingseat',
            name='unique_seat_booking',
        ),
        migrations.AddConstraint(
            model_name='bookingseat',
            constraint=models.UniqueConstraint(fields=('booking', 'seat'), name='unique_booking_seat'),
        ),
    ]
